# Generated by Django 3.2.3 on 2021-06-21 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca_Bicicleta',
            fields=[
                ('id_marca', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Bicicleta',
            fields=[
                ('id_tipo_bicicleta', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion_bicicleta', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id_bicicleta', models.IntegerField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('aro', models.IntegerField()),
                ('nro_cambios', models.IntegerField()),
                ('marca_bicicleta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.marca_bicicleta')),
                ('tipo_bicicleta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipo_bicicleta')),
            ],
        ),
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('id_arriendo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('precio_dia', models.IntegerField()),
                ('bicicleta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.bicicleta')),
            ],
        ),
    ]
