# Generated by Django 3.2.3 on 2021-06-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210621_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='arriendo',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
